name: "Sync"

on:
  schedule:
    - cron:  '0 0 * * *'  # This sets the action to run every day at midnight 

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Mirror and Sync the repo
      run: |
        git config --global user.name 'Hongyi Zhao'
        git config --global user.email 'hongyi.zhao@gmail.com'
        git clone --mirror git://git.lyx.org/lyx.git
        cd lyx
        git remote set-url --push origin https://github.com/hongyi-zhao/lyx.git
        git fetch -p origin
        git push --mirror
