name: Sync with upstream repository

on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours, can be adjusted as needed

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup git
        run: |
          git config user.name "Hongyi Zhao"
          git config user.email "hongyi.zhao@gmail.com"

      - name: Add remote upstream
        run: git remote add upstream git://git.lyx.org/lyx

      - name: Fetch changes from upstream
        run: git fetch upstream --verbose

      - name: Merge changes from upstream
        run: git merge upstream/master --allow-unrelated-histories --verbose # Ensure the upstream branch is correct

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master # Ensure branch name matches the branch you want to sync with
